/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * BIRD ACADEMY ENTERPRISE — SUBSCRIPTION TIER MATRIX AUDIT & CAPABILITIES E2E SUITE
 * Mission: SUBSCRIPTION-TIER-MATRIX-FINAL-01
 * 
 * Playwright E2E Audit covering:
 * 1. FREE Baseline User: Complete functional audit of core breeding, bird, cage, couple, reproduction, health, feeding modules.
 * 2. PREMIUM Capability Matrix: User data & bird context authorization, breeding/health analysis, restriction on advanced analysis.
 * 3. PRO Capability Matrix: Unlimited quota, advanced genealogy/financial analysis, report assistance.
 * 4. Permission Security & Restriction Messages: Exact denial reasons generated by AssistantPermissionService.
 * 5. Dynamic Tier & License Transitions: Active Beta/Free -> Commercial -> Enterprise.
 * 6. Persistence: Retaining license and data across reload and tab switching.
 * 7. Real Offline Execution: Playwright context.setOffline(true) audit.
 * 8. Mobile Viewport: 375x812 drawer navigation and zero horizontal overflow.
 * 9. Multilingual & RTL: FR, EN, AR (dir="rtl"), ES, IT compliance.
 * 10. System Health: Zero uncaught fatal exceptions or UI crashes.
 */

import { test, expect, Page } from '@playwright/test';
import { CryptoService } from '../../src/features/licensing/services/CryptoService';
import { License, LicenseType } from '../../src/features/licensing/types/licensing';
import { AssistantPermissionProvider, TIER_CONFIGURATIONS } from '../../src/features/assistant/providers/context/AssistantPermissionProvider';
import { AssistantPermissionService } from '../../src/features/assistant/services/AssistantPermissionService';

/**
 * Helper to generate cryptographically signed licenses for testing
 */
async function createValidTestLicense(
  type: LicenseType = 'beta',
  status: 'active' | 'expired' | 'revoked' = 'active',
  holderName: string = 'Éleveur Test Playwright',
  daysRemaining: number = 90
): Promise<License> {
  const typeTagMap: Record<LicenseType, string> = {
    beta: 'BETA',
    commercial: 'COMM',
    permanent: 'PERM',
    temporary: 'TEMP',
    enterprise: 'ENTP',
    association: 'ASSO',
    veterinary: 'VETE',
  };

  const tag = typeTagMap[type] || 'COMM';
  const id = `lic_audit_${type}_${Date.now()}`;
  const key = `LMSE-${tag}-8888-7777-6666`;
  const issuedAt = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString();
  
  let expiresAt: string | null = null;
  if (type !== 'permanent') {
    if (status === 'expired') {
      expiresAt = new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString();
    } else {
      expiresAt = new Date(Date.now() + daysRemaining * 24 * 60 * 60 * 1000).toISOString();
    }
  }

  const maxDevices = type === 'enterprise' ? 25 : (type === 'commercial' ? 3 : 2);
  const features = type === 'enterprise'
    ? ['core', 'unlimited_birds', 'pedigree', 'statistics', 'export_pdf', 'multi_user']
    : (type === 'commercial' ? ['core', 'unlimited_birds', 'pedigree', 'statistics'] : ['core', 'beta_access']);

  const payloadToSign = `${id}:${key}:${holderName}:${type}:${issuedAt}:${expiresAt || 'NEVER'}:${maxDevices}`;
  const checksum = await CryptoService.sha256(payloadToSign);
  const signature = await CryptoService.generateSignature(checksum, CryptoService.getPublicVerificationKey());

  return {
    id,
    key,
    holderName,
    type,
    status: status === 'revoked' ? 'revoked' : (status === 'expired' ? 'expired' : 'active'),
    issuedAt,
    expiresAt,
    policy: {
      maxDevices,
      allowOfflineActivation: true,
      allowTransfer: true,
      features,
    },
    activations: [
      {
        id: `act_${Date.now()}`,
        licenseId: id,
        licenseKey: key,
        fingerprint: {
          deviceId: 'dev_playwright_matrix_audit',
          os: 'Web',
          browserHash: 'browser_hash_matrix_audit',
          screenSpec: '1920x1080',
          timezone: 'Europe/Paris',
          language: 'fr',
          hardwareConcurrency: 8,
          createdAt: issuedAt,
          lastSeenAt: new Date().toISOString(),
        },
        activatedAt: issuedAt,
        lastVerifiedAt: new Date().toISOString(),
        isOffline: true,
      }
    ],
    revokedAt: status === 'revoked' ? new Date().toISOString() : null,
    revocationReason: status === 'revoked' ? 'Audit de révocation' : null,
    checksum,
    signature,
    metadata: { testSuite: 'SUBSCRIPTION-TIER-MATRIX-FINAL-01' },
  };
}

/**
 * Reliably seeds localStorage state before reloading
 */
async function setupInitialStorage(
  page: Page,
  options: {
    license?: License | null;
    wizardCompleted?: boolean;
    demoActive?: boolean;
    language?: 'fr' | 'en' | 'ar' | 'es' | 'it';
    timeMarker?: string;
  }
) {
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.evaluate((opts) => {
    localStorage.clear();

    if (opts.license) {
      localStorage.setItem('bird_academy_lmse_active_license', JSON.stringify(opts.license));
      localStorage.setItem('bird_academy_lmse_all_licenses', JSON.stringify([opts.license]));
    }

    if (opts.wizardCompleted) {
      localStorage.setItem('bird_academy_wizard_completed', 'true');
    }

    if (opts.demoActive) {
      localStorage.setItem('bird_academy_demo_active', 'true');
    }

    if (opts.language) {
      localStorage.setItem('bird_academy_language', opts.language);
    }

    if (opts.timeMarker) {
      localStorage.setItem('bird_academy_lmse_last_known_timestamp', opts.timeMarker);
    }
  }, options);
  await page.reload({ waitUntil: 'domcontentloaded' });
}

function attachErrorTracker(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (err) => {
    errors.push(`[PageError] ${err.message}`);
  });
  page.on('console', (msg) => {
    if (msg.type() === 'error') {
      const text = msg.text();
      if (!text.includes('favicon') && !text.includes('404') && !text.includes('[BOOT-')) {
        errors.push(`[ConsoleError] ${text}`);
      }
    }
  });
  return errors;
}

test.describe('SUBSCRIPTION-TIER-MATRIX-FINAL-01 : AUDIT COMMERCIAL & FONCTIONNEL E2E', () => {

  test.beforeEach(async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
  });

  // --------------------------------------------------------------------------
  // 1. AUDIT DU NIVEAU FREE (DÉCOUVERTE & GESTION DE BASE)
  // --------------------------------------------------------------------------
  test('TC-M01 : Niveau FREE -> Accès complet et sans restriction aux 14 modules essentiels de gestion du cheptel', async ({ page }) => {
    const errorTracker = attachErrorTracker(page);
    const freeLicense = await createValidTestLicense('beta', 'active', 'Éleveur Découverte Free');
    await setupInitialStorage(page, {
      license: freeLicense,
      wizardCompleted: true,
      demoActive: true,
      language: 'fr',
    });

    // 1. Dashboard de base
    await expect(page.locator('[data-testid="desktop-sidebar"]')).toBeVisible({ timeout: 15000 });
    await expect(page.getByRole('heading', { name: /Tableau de bord/i })).toBeVisible();

    // 2. Gestion des oiseaux
    await page.locator('[data-testid="nav-item-canaris"]').click();
    await expect(page.locator('#main-content').getByRole('heading', { name: 'Oiseaux' })).toBeVisible();
    await expect(page.locator('#main-content')).toContainText(/Canari|Oiseau|Bague/i);

    // 3. Habitat & Cages
    await page.locator('[data-testid="nav-item-cages"]').click();
    await expect(page.locator('#main-content')).toContainText(/Cage|Volière|Habitat/i);

    // 4. Couples
    await page.locator('[data-testid="nav-item-couples"]').click();
    await expect(page.locator('#main-content')).toContainText(/Couple/i);

    // 5. Reproduction
    await page.locator('[data-testid="nav-item-reproduction"]').click();
    await expect(page.locator('#main-content')).toContainText(/Reproduction/i);

    // 6. Santé
    await page.locator('[data-testid="nav-item-sante"]').click();
    await expect(page.locator('#main-content')).toContainText(/Soins|Traitements|Santé/i);

    // 7. Alimentation
    await page.locator('[data-testid="nav-item-alimentation"]').click();
    await expect(page.locator('#main-content')).toContainText(/Alimentation|Ration/i);

    // 8. Calendrier
    await page.locator('[data-testid="nav-item-calendrier"]').click();
    await expect(page.locator('#main-content')).toBeVisible();

    // 9. Génétique
    await page.locator('[data-testid="nav-item-genetics"]').click();
    await expect(page.locator('#main-content')).toContainText(/Génétique/i);

    // 10. Bird Intelligence
    await page.locator('[data-testid="nav-item-intelligence"]').click();
    await expect(page.locator('#main-content')).toContainText(/Intelligence|Score/i);

    // 11. Statistiques
    await page.locator('[data-testid="nav-item-statistiques"]').click();
    await expect(page.locator('#main-content')).toContainText(/Centre décisionnel|Analyses|Performance|Statistiques/i);

    // 12. Référentiel Biologique
    await page.locator('[data-testid="nav-item-reference_biologique"]').click();
    await expect(page.locator('#main-content')).toContainText(/Référence Biologique|Registre|Espèces/i);

    // 13. Dépenses & Ventes
    await page.locator('[data-testid="nav-item-depenses"]').click();
    await expect(page.locator('#main-content')).toContainText(/Dépenses/i);
    await page.locator('[data-testid="nav-item-ventes"]').click();
    await expect(page.locator('#main-content')).toContainText(/Ventes/i);

    // 14. Paramètres
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByRole('heading', { name: "Paramètres de l'Application" })).toBeVisible();

    expect(errorTracker.filter(e => e.includes('PageError'))).toHaveLength(0);
  });

  // --------------------------------------------------------------------------
  // 2. AUDIT DE LA MATRICE DES CAPABILITIES ASSISTANT IA (FREE, PREMIUM, PRO)
  // --------------------------------------------------------------------------
  test('TC-M02 : Matrice Assistant IA -> Vérification stricte des permissions et quotas par niveau', async () => {
    // 1. FREE : Quota 10, Connaissances générales & biologiques uniquement
    const freeCfg = TIER_CONFIGURATIONS.FREE;
    expect(freeCfg.tier).toBe('FREE');
    expect(freeCfg.maxQueriesPerDay).toBe(10);
    expect(freeCfg.allowUserDataAccess).toBe(false);
    expect(freeCfg.allowIntelligenceAccess).toBe(false);
    expect(freeCfg.allowAdvancedAnalysis).toBe(false);
    expect(freeCfg.capabilities).toEqual(['GENERAL_KNOWLEDGE', 'BIOLOGICAL_KNOWLEDGE']);

    const freeBioCheck = AssistantPermissionService.checkAuthorization('FREE', 'GENERAL_BIOLOGY');
    expect(freeBioCheck.isAuthorized).toBe(true);

    const freeBirdCheck = AssistantPermissionService.checkAuthorization('FREE', 'USER_BIRD');
    expect(freeBirdCheck.isAuthorized).toBe(false);
    expect(freeBirdCheck.reason).toContain('PREMIUM');

    // 2. PREMIUM : Quota 100, Accès au cheptel, reproduction, santé, explications Bird Intelligence
    const premiumCfg = TIER_CONFIGURATIONS.PREMIUM;
    expect(premiumCfg.tier).toBe('PREMIUM');
    expect(premiumCfg.maxQueriesPerDay).toBe(100);
    expect(premiumCfg.allowUserDataAccess).toBe(true);
    expect(premiumCfg.allowIntelligenceAccess).toBe(true);
    expect(premiumCfg.allowAdvancedAnalysis).toBe(false);
    expect(premiumCfg.capabilities).toContain('BIRD_CONTEXT');
    expect(premiumCfg.capabilities).toContain('BREEDING_ANALYSIS');
    expect(premiumCfg.capabilities).toContain('HEALTH_ANALYSIS');
    expect(premiumCfg.capabilities).toContain('INTELLIGENCE_EXPLANATION');

    const premBirdCheck = AssistantPermissionService.checkAuthorization('PREMIUM', 'USER_BIRD');
    expect(premBirdCheck.isAuthorized).toBe(true);

    const premGenealogyCheck = AssistantPermissionService.checkAuthorization('PREMIUM', 'USER_GENEALOGY');
    expect(premGenealogyCheck.isAuthorized).toBe(false);
    expect(premGenealogyCheck.reason).toContain('PRO');

    // 3. PRO : Quota Illimité, Analyses généalogiques & financières avancées, assistance aux rapports
    const proCfg = TIER_CONFIGURATIONS.PRO;
    expect(proCfg.tier).toBe('PRO');
    expect(proCfg.maxQueriesPerDay).toBeNull();
    expect(proCfg.allowUserDataAccess).toBe(true);
    expect(proCfg.allowIntelligenceAccess).toBe(true);
    expect(proCfg.allowAdvancedAnalysis).toBe(true);
    expect(proCfg.capabilities).toContain('ADVANCED_ANALYSIS');
    expect(proCfg.capabilities).toContain('REPORT_ASSISTANCE');

    const proGenealogyCheck = AssistantPermissionService.checkAuthorization('PRO', 'USER_GENEALOGY');
    expect(proGenealogyCheck.isAuthorized).toBe(true);

    const proReportCheck = AssistantPermissionService.checkAuthorization('PRO', 'REPORT_EXPLANATION');
    expect(proReportCheck.isAuthorized).toBe(true);
  });

  // --------------------------------------------------------------------------
  // 3. AUDIT DES RESTRICTIONS ET MESSAGES DE REFUS
  // --------------------------------------------------------------------------
  test('TC-M03 : Messages de restriction explicites et clairs pour chaque niveau d\'élévation requis', async () => {
    // Check refusal messages for FREE attempting PREMIUM capability
    const freeToPrem1 = AssistantPermissionService.checkAuthorization('FREE', 'USER_BREEDING');
    expect(freeToPrem1.isAuthorized).toBe(false);
    expect(freeToPrem1.reason).toBe("La fonctionnalité 'BREEDING_ANALYSIS' nécessite le niveau PREMIUM.");

    const freeToPrem2 = AssistantPermissionService.checkAuthorization('FREE', 'USER_HEALTH');
    expect(freeToPrem2.isAuthorized).toBe(false);
    expect(freeToPrem2.reason).toBe("La fonctionnalité 'HEALTH_ANALYSIS' nécessite le niveau PREMIUM.");

    const freeToPrem3 = AssistantPermissionService.checkAuthorization('FREE', 'INTELLIGENCE_EXPLANATION');
    expect(freeToPrem3.isAuthorized).toBe(false);
    expect(freeToPrem3.reason).toBe("La fonctionnalité 'INTELLIGENCE_EXPLANATION' nécessite le niveau PREMIUM.");

    // Check refusal messages for FREE and PREMIUM attempting PRO capability
    const freeToPro = AssistantPermissionService.checkAuthorization('FREE', 'USER_FINANCE');
    expect(freeToPro.isAuthorized).toBe(false);
    expect(freeToPro.reason).toBe("La fonctionnalité 'ADVANCED_ANALYSIS' nécessite le niveau PRO.");

    const premToPro = AssistantPermissionService.checkAuthorization('PREMIUM', 'REPORT_EXPLANATION');
    expect(premToPro.isAuthorized).toBe(false);
    expect(premToPro.reason).toBe("La fonctionnalité 'REPORT_ASSISTANCE' nécessite le niveau PRO.");
  });

  // --------------------------------------------------------------------------
  // 4. AUDIT DES TRANSITIONS DE LICENCE & STATUTS LMSE
  // --------------------------------------------------------------------------
  test('TC-M04 : Transitions de licence LMSE -> Mise à jour dynamique de l\'interface utilisateur', async ({ page }) => {
    // 1. Initialisation avec Licence Beta (BETA / Active)
    const betaLic = await createValidTestLicense('beta', 'active', 'Titulaire Beta Test', 60);
    await setupInitialStorage(page, { license: betaLic, wizardCompleted: true, language: 'fr' });

    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByText('ACTIVE').first()).toBeVisible();
    await expect(page.getByText('Titulaire Beta Test')).toBeVisible();

    // 2. Transition vers Licence Commerciale (COMMERCIAL / Active)
    const commLic = await createValidTestLicense('commercial', 'active', 'Élevage Commercial Sud', 120);
    await page.evaluate((lic) => {
      localStorage.setItem('bird_academy_lmse_active_license', JSON.stringify(lic));
    }, commLic);

    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByText('COMMERCIAL').first()).toBeVisible();
    await expect(page.getByText('Élevage Commercial Sud')).toBeVisible();

    // 3. Transition vers Licence Enterprise (ENTERPRISE / Multi-postes)
    const entLic = await createValidTestLicense('enterprise', 'active', 'Centrale Avicole Nationale', 365);
    await page.evaluate((lic) => {
      localStorage.setItem('bird_academy_lmse_active_license', JSON.stringify(lic));
    }, entLic);

    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByText('ENTERPRISE').first()).toBeVisible();
    await expect(page.getByText('Centrale Avicole Nationale')).toBeVisible();
  });

  // --------------------------------------------------------------------------
  // 5. AUDIT DE FONCTIONNEMENT 100% HORS LIGNE (OFFLINE-FIRST)
  // --------------------------------------------------------------------------
  test('TC-M05 : Fonctionnement 100% hors ligne réel (Playwright setOffline) sans serveur ni dépendance cloud', async ({ page, context }) => {
    const errorTracker = attachErrorTracker(page);
    const offlineLic = await createValidTestLicense('commercial', 'active', 'Éleveur 100% Offline');
    await setupInitialStorage(page, {
      license: offlineLic,
      wizardCompleted: true,
      demoActive: true,
      language: 'fr',
    });

    await expect(page.locator('[data-testid="desktop-sidebar"]')).toBeVisible({ timeout: 15000 });

    // Pre-warm lazy routes for offline simulation
    await page.locator('[data-testid="nav-item-canaris"]').click();
    await page.locator('[data-testid="nav-item-cages"]').click();
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await page.locator('[data-testid="nav-item-dashboard"]').click();

    // 1. Coupure réseau totale
    await context.setOffline(true);

    // 2. Navigation et opérations sans réseau
    await page.locator('[data-testid="nav-item-canaris"]').click();
    await expect(page.locator('#main-content').getByRole('heading', { name: 'Oiseaux' })).toBeVisible();

    await page.locator('[data-testid="nav-item-cages"]').click();
    await expect(page.locator('#main-content')).toBeVisible();

    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByRole('heading', { name: "Paramètres de l'Application" })).toBeVisible();
    await expect(page.getByText('Éleveur 100% Offline')).toBeVisible();

    // Rétablissement réseau
    await context.setOffline(false);

    expect(errorTracker.filter(e => e.includes('PageError'))).toHaveLength(0);
  });

  // --------------------------------------------------------------------------
  // 6. AUDIT DE PERSISTANCE APRÈS NAVIGATION ET RECHARGEMENT
  // --------------------------------------------------------------------------
  test('TC-M06 : Persistance de l\'état de licence et des données après actualisation', async ({ page }) => {
    const permLic = await createValidTestLicense('permanent', 'active', 'Élevage Perpétuel');
    await setupInitialStorage(page, {
      license: permLic,
      wizardCompleted: true,
      demoActive: true,
      language: 'fr',
    });

    await expect(page.getByRole('heading', { name: /Tableau de bord/i })).toBeVisible({ timeout: 15000 });

    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByText('Élevage Perpétuel')).toBeVisible();
    await expect(page.getByText('PERMANENT').first()).toBeVisible();

    // Rechargement complet
    await page.reload({ waitUntil: 'domcontentloaded' });

    // Reste authentifié et sans interruption
    await expect(page.getByRole('heading', { name: /Tableau de bord/i })).toBeVisible({ timeout: 15000 });
    await expect(page.locator('[data-testid="desktop-sidebar"]')).toBeVisible();
  });

  // --------------------------------------------------------------------------
  // 7. AUDIT MOBILE (375x812) & RESPONSIVE DESIGN
  // --------------------------------------------------------------------------
  test('TC-M07 : Viewport Mobile (375x812) -> Navigation par tiroir, lisibilité et zéro débordement', async ({ page }) => {
    const mobileLic = await createValidTestLicense('beta', 'active', 'Auditeur Mobile');
    await setupInitialStorage(page, {
      license: mobileLic,
      wizardCompleted: true,
      demoActive: true,
      language: 'fr',
    });

    await page.setViewportSize({ width: 375, height: 812 });

    // Sidebar desktop cachée
    await expect(page.locator('[data-testid="desktop-sidebar"]')).not.toBeVisible();

    // Bouton de menu burger visible
    const burger = page.getByRole('button', { name: /menu/i });
    await expect(burger).toBeVisible();

    // Zéro débordement horizontal
    const hasHorizontalOverflow = await page.evaluate(() => {
      return document.documentElement.scrollWidth > document.documentElement.clientWidth;
    });
    expect(hasHorizontalOverflow).toBe(false);

    // Ouverture tiroir mobile
    await burger.click();
    await expect(page.locator('#mobile-navigation-drawer')).toBeVisible();

    // Clic sur Oiseaux depuis le tiroir
    await page.locator('#mobile-navigation-drawer').getByText(/Canaris|Oiseaux/i).first().click();
    await expect(page.locator('#main-content').getByRole('heading', { name: 'Oiseaux' })).toBeVisible();
  });

  // --------------------------------------------------------------------------
  // 8. AUDIT MULTILINGUE (FR, EN, AR AVEC RTL, ES, IT)
  // --------------------------------------------------------------------------
  test('TC-M08 : Multilingue complet (5 langues) et direction RTL en arabe', async ({ page }) => {
    const polyglotLic = await createValidTestLicense('commercial', 'active', 'International Breeder');
    await setupInitialStorage(page, {
      license: polyglotLic,
      wizardCompleted: true,
      demoActive: true,
      language: 'fr',
    });

    await page.locator('[data-testid="nav-item-parametres"]').click();

    // 1. Français (FR)
    await expect(page.getByRole('heading', { name: "Paramètres de l'Application" })).toBeVisible();
    await expect(page.getByText(/Licence & Certification/i)).toBeVisible();

    // 2. Anglais (EN)
    await page.evaluate(() => localStorage.setItem('bird_academy_language', 'en'));
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByRole('heading', { name: 'Application Settings' })).toBeVisible();
    await expect(page.getByText(/License & Certification/i)).toBeVisible();

    // 3. Arabe (AR) avec RTL
    await page.evaluate(() => localStorage.setItem('bird_academy_language', 'ar'));
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByRole('heading', { name: 'إعدادات التطبيق' })).toBeVisible();
    await expect(page.getByText(/الترخيص والإعتماد/i)).toBeVisible();

    const isRtl = await page.evaluate(() => {
      return document.documentElement.dir === 'rtl' || document.querySelector('.rtl') !== null || document.querySelector('[dir="rtl"]') !== null;
    });
    expect(isRtl).toBe(true);

    // 4. Espagnol (ES)
    await page.evaluate(() => localStorage.setItem('bird_academy_language', 'es'));
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByRole('heading', { name: 'Ajustes de la Aplicación' })).toBeVisible();
    await expect(page.getByText(/Licencia y Certificación/i)).toBeVisible();

    // 5. Italien (IT)
    await page.evaluate(() => localStorage.setItem('bird_academy_language', 'it'));
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('[data-testid="nav-item-parametres"]').click();
    await expect(page.getByRole('heading', { name: "Impostazioni dell'Applicazione" })).toBeVisible();
    await expect(page.getByText(/Licenza e Certificazione/i)).toBeVisible();
  });

  // --------------------------------------------------------------------------
  // 9. AUDIT D'INTÉGRITÉ CONSOLE ET SANTÉ SYSTÈME
  // --------------------------------------------------------------------------
  test('TC-M09 : Santé globale et absence de crash / erreurs fatales console', async ({ page }) => {
    const errorTracker = attachErrorTracker(page);
    const validLic = await createValidTestLicense('enterprise', 'active', 'Contrôle Santé');
    await setupInitialStorage(page, {
      license: validLic,
      wizardCompleted: true,
      demoActive: true,
      language: 'fr',
    });

    const tabIds = [
      'nav-item-canaris',
      'nav-item-cages',
      'nav-item-couples',
      'nav-item-reproduction',
      'nav-item-sante',
      'nav-item-alimentation',
      'nav-item-calendrier',
      'nav-item-genetics',
      'nav-item-intelligence',
      'nav-item-statistiques',
      'nav-item-reference_biologique',
      'nav-item-depenses',
      'nav-item-ventes',
      'nav-item-parametres',
      'nav-item-dashboard',
    ];

    for (const tabId of tabIds) {
      const tabLocator = page.locator(`[data-testid="${tabId}"]`);
      if (await tabLocator.isVisible()) {
        await tabLocator.click();
        await page.waitForTimeout(50);
      }
    }

    const fatalErrors = errorTracker.filter(e => e.includes('PageError'));
    expect(fatalErrors).toHaveLength(0);
  });

});
